name: Publish Nuget package
on: [push]

jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: publish nuget
        run: |
          dotnet pack -c Release -o fun.nupkg ./WebApiModels/WebApiModels.csproj
          dotnet nuget push fun.nupkg -s https://github.com/observian/poc--github-actions