name: Publish Nuget package
on: [push]

jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1

      - name: publish nuget
        run: |
          dotnet pack -c Release -o . ./WebApiModels/WebApiModels.csproj
          echo "${{ secrets.NUGET_CONFIG }}" > nuget.config
          
          cat nuget.config
          
          