name: Publish Nuget package
on: [push]

jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1

      - name: publish nuget
        run: |
          dotnet pack -c Release -o . ./WebApiModels/WebApiModels.csproj
          nuget push *.nupkg -apiKey ${{ secrets.GITHUB_TOKEN }} -source https://nuget.pkg.github.com/observian/poc--github-actions
          