name: Publish Nuget package
on: [push]

jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
      - name: publish nuget
        run: |
          dotnet pack -c Release -o fun.nupkg ./WebApiModels/WebApiModels.csproj
          dotnet nuget push fun.nupkg